### ISSUE TITLE
[Question]  Set data in a config file

### ISSUE THREAD

**Issue by sweatyrayan** [aieuo/Mineflow#112]
### Question

Idk how exactly config files work, but I tried it.

I created a config file with the variable of {target.name}but when I try to set a data in the config file of {target.name} it gives me a error that its not a config file variable.

So I basically want to create a config file for each player, and then add data to it
### Plugin Version

latest

**Comment by aieuo** [comment]
The `<config>` field of the `Set a data in config file` should use the value you entered in the `<result>` field of the `Create a config file`.
![image](https://user-images.githubusercontent.com/35859665/152529361-9ebb5308-5183-4b72-b0f7-3ad7f842a585.png)


By the way, I recommend adding all player data in one file rather than creating a file for each player to avoid creating many files. like [this](https://github.com/aieuo/MineflowExamples/blob/master/Counter.json)

**Comment by sweatyrayan** [comment]
Ok thanks,
Do you also know how make a proximity chat, for example the player sends a message and the only players near him can see the message

**Comment by aieuo** [comment]
I think you can make it with the `When a player chats` trigger and following actions

- `Cancel event`
- `[foreach] Repeat for the elements of the list` (server.players as key => player)
  - `Get the distance between two positions` (target, player)
  - `if` ({distance} < 10)
    - `Send message to chat field` (player, {messages})

**Comment by sweatyrayan** [comment]
thanks
